/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.baitap;

import javax.swing.JOptionPane;

/**
 *
 * @author neroooo
 */
public class Bai_6_Cong_Tru_Nhan_Chia extends javax.swing.JFrame {

    /**
     * Creates new form Bai_6_Cong_Tru_Nhan_Chia
     */
    public Bai_6_Cong_Tru_Nhan_Chia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCTNC = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlGiai = new javax.swing.JButton();
        pnlXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        lblNhapA = new javax.swing.JLabel();
        txtNhapA = new javax.swing.JTextField();
        txtNhapB = new javax.swing.JTextField();
        lblNhapB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioCong = new javax.swing.JRadioButton();
        radioTru = new javax.swing.JRadioButton();
        radioChia = new javax.swing.JRadioButton();
        radioNhan = new javax.swing.JRadioButton();
        txtKQ = new javax.swing.JTextField();
        lblKQ = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        pnlEnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        pnlTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pnlTitle.setForeground(new java.awt.Color(102, 102, 255));
        pnlTitle.setText("Cộng Trừ Nhân Chia");
        pnlTop.add(pnlTitle);

        mainPanel.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác Vụ"));

        pnlGiai.setText("Giải");
        pnlGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlGiaiActionPerformed(evt);
            }
        });
        pnlLeft.add(pnlGiai);

        pnlXoa.setText("Xóa");
        pnlXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlXoaActionPerformed(evt);
            }
        });
        pnlLeft.add(pnlXoa);

        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlLeft.add(btnThoat);

        pnlRight.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập 2 số a và b:"));

        lblNhapA.setText("Nhập a:");

        lblNhapB.setText("Nhập b:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn phép toán"));

        btnCTNC.add(radioCong);
        radioCong.setText("Cộng");

        btnCTNC.add(radioTru);
        radioTru.setText("Trừ");

        btnCTNC.add(radioChia);
        radioChia.setText("Chia");

        btnCTNC.add(radioNhan);
        radioNhan.setText("Nhân");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioCong)
                .addGap(18, 18, 18)
                .addComponent(radioTru)
                .addGap(18, 18, 18)
                .addComponent(radioNhan)
                .addGap(18, 18, 18)
                .addComponent(radioChia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCong)
                    .addComponent(radioTru)
                    .addComponent(radioNhan)
                    .addComponent(radioChia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtKQ.setEditable(false);

        lblKQ.setText("Kết quả:");

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addComponent(lblNhapB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhapB))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addComponent(lblNhapA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhapA, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblKQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKQ))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapA)
                    .addComponent(txtNhapA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapB)
                    .addComponent(txtNhapB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKQ)
                    .addComponent(txtKQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlEnd.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        pnlEnd.setText("Have Fun");
        pnlBottom.add(pnlEnd);

        mainPanel.add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlGiaiActionPerformed
        // TODO add your handling code here:
        String sa = txtNhapA.getText();
        String sb = txtNhapB.getText();
        int a=0,b=0;
        try
        {
                a=Integer.parseInt(sa);
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, "Nhập sai định dạng!");
                txtNhapA.selectAll();
                txtNhapA.requestFocus();
                return;
        }
                try
        {
                b=Integer.parseInt(sa);
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, "Nhập sai định dạng!");
                txtNhapB.selectAll();
                txtNhapB.requestFocus();
                return;
        }
        double kq=0;
        if(radioCong.isSelected())
        {
                kq=(a+b);
                txtKQ.setText(kq+"");
        }
        else if(radioTru.isSelected())
        {
                kq=(a-b);
                txtKQ.setText(kq+"");
        }
        else if(radioNhan.isSelected())
        {
                kq=(a*b);
                txtKQ.setText(kq+"");
        }
        else if(radioChia.isSelected())
        {
                kq=a*1.0/b*1.0;
                txtKQ.setText(kq+"");
        }
        else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn phép toán");
        }
        
    }//GEN-LAST:event_pnlGiaiActionPerformed

    private void pnlXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlXoaActionPerformed
        // TODO add your handling code here:
        txtKQ.setText("");
        txtNhapA.setText("");
        txtNhapB.setText("");
    }//GEN-LAST:event_pnlXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    int ret=JOptionPane.showConfirmDialog(null, "Muốn thoát hả?", "Thoát", JOptionPane.YES_NO_OPTION);
    if(ret==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_6_Cong_Tru_Nhan_Chia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_6_Cong_Tru_Nhan_Chia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_6_Cong_Tru_Nhan_Chia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_6_Cong_Tru_Nhan_Chia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_6_Cong_Tru_Nhan_Chia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnCTNC;
    private javax.swing.JButton btnThoat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblKQ;
    private javax.swing.JLabel lblNhapA;
    private javax.swing.JLabel lblNhapB;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JLabel pnlEnd;
    private javax.swing.JButton pnlGiai;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JLabel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JButton pnlXoa;
    private javax.swing.JRadioButton radioChia;
    private javax.swing.JRadioButton radioCong;
    private javax.swing.JRadioButton radioNhan;
    private javax.swing.JRadioButton radioTru;
    private javax.swing.JTextField txtKQ;
    private javax.swing.JTextField txtNhapA;
    private javax.swing.JTextField txtNhapB;
    // End of variables declaration//GEN-END:variables
}
