/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.baitap;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author neroooo
 */
public class Bai_7_Thao_Tac_JList extends javax.swing.JFrame {

    /**
     * Creates new form Bai_7_Thao_Tac_JList
     */
    public Bai_7_Thao_Tac_JList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        pnlMain = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlTacVu = new javax.swing.JPanel();
        btnToSoChan = new javax.swing.JButton();
        btnToSoLe = new javax.swing.JButton();
        btnToSoNguyenTo = new javax.swing.JButton();
        btnBoTo = new javax.swing.JButton();
        btnXoaToDen = new javax.swing.JButton();
        btnTong = new javax.swing.JButton();
        pnlThongTin = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        checkSoAm = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMain = new javax.swing.JList<>();
        pnlBottom = new javax.swing.JPanel();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Thao tác trên JList - Checkbox");
        pnlTop.add(jLabel1);

        pnlMain.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn tác vụ"));
        pnlTacVu.setLayout(new javax.swing.BoxLayout(pnlTacVu, javax.swing.BoxLayout.Y_AXIS));

        btnToSoChan.setText("Tô đen số chẵn");
        btnToSoChan.setActionCommand("Tô đen số chẵn");
        pnlTacVu.add(btnToSoChan);

        btnToSoLe.setText("Tô đen số lẽ");
        pnlTacVu.add(btnToSoLe);

        btnToSoNguyenTo.setText("Tô đen số nguyên tố");
        pnlTacVu.add(btnToSoNguyenTo);

        btnBoTo.setText("Bỏ tô đen");
        pnlTacVu.add(btnBoTo);

        btnXoaToDen.setMnemonic('X');
        btnXoaToDen.setText("Xóa các giá trị đang tô đen");
        btnXoaToDen.setActionCommand("Xóa các giá trị tô đen");
        pnlTacVu.add(btnXoaToDen);

        btnTong.setText("Tổng giá trị tronmg JList");
        pnlTacVu.add(btnTong);

        pnlThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập thông tin"));

        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        checkSoAm.setText("Cho nhập số âm");

        jScrollPane2.setViewportView(listMain);

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkSoAm)))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhap)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSoAm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addComponent(pnlTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMain.add(pnlCenter, java.awt.BorderLayout.CENTER);

        btnDong.setText("Đóng chương trình");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        pnlBottom.add(btnDong);

        pnlMain.add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
            // TODO add your handling code here:
        int dong = JOptionPane.showConfirmDialog(null, "Đóng chương trình", "Thoát", JOptionPane.YES_OPTION);
        if(dong==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        String nhap = txtNhap.getText();
        int in = 0;
        int check = 0;
        try{
            check = Integer.parseInt(nhap);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nhập sai định dạng");
            txtNhap.selectAll();
            txtNhap.requestFocus();
            in = Integer.parseInt(nhap);
        }
        if(!checkSoAm.isSelected() && in < 0){
            JOptionPane.showMessageDialog(null, "Không được nhập số âm");
        }
        else{
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_7_Thao_Tac_JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_7_Thao_Tac_JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_7_Thao_Tac_JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_7_Thao_Tac_JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_7_Thao_Tac_JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoTo;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnToSoChan;
    private javax.swing.JButton btnToSoLe;
    private javax.swing.JButton btnToSoNguyenTo;
    private javax.swing.JButton btnTong;
    private javax.swing.JButton btnXoaToDen;
    private javax.swing.JCheckBox checkSoAm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Integer> listMain;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTacVu;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables
}
